### PR TITLE
Working version of Sprint 1

### PR DESCRIPTION
**Pull request by imcodingideas**
Introduces:
- formik
- context
- styled-components
- eslint
- webpack
- local storage state
- envirement variables

Removes
- node scss
- create react app

### CODE REVIEW

**Comment by imcodingideas** [comment]
@hiimalexjgarcia looks like the last deploy failed because of netlify looking for the build folder. I renamed dist to build so this can deploy.

**Comment by imcodingideas** [comment]
@hiimalexjgarcia and @josephmturner you can now update the user settings as well!

**Comment by imcodingideas** [comment]
@hiimalexjgarcia 

The initialState is now in a new file. The background configuration is now working. The points font size increased.

**Comment by imcodingideas** [comment]
@hiimalexjgarcia added username stuff today.

**Comment by hiimalexjgarcia** [comment]
Addresses issue #6

**Comment by hiimalexjgarcia** [comment]
Addresses issue #12

**Comment by hiimalexjgarcia** [comment]
Addresses issue #14

**Pull request merged**
